updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status jenkinsSnapshotGit --context "$step_name"

pipelines:
  - name: build_jenkins_snapshot
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: maven
            tag: 3.6.3-adoptopenjdk-8
      environmentVariables:
        readOnly:
          CI: "true"
          M2_HOME: $MAVEN_HOME
          JFROG_CLI_BUILD_NAME: "jenkins-plugin-dev"
          JFROG_CLI_BUILD_NUMBER: $run_number

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: jenkinsSnapshotGit
          integrations:
            - name: jfrog
            - name: ojo
        execution:
          onStart:
            - apt update && apt install -y gettext-base jq
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_jenkinsSnapshotGit_resourcePath

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog rt c jfrog --url $int_jfrog_rt_url --user $int_jfrog_rt_user --password $int_jfrog_rt_password
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt mvnc
              --server-id-resolve ojo --repo-resolve-releases libs-release --repo-resolve-snapshots libs-snapshot
              --server-id-deploy jfrog --repo-deploy-releases libs-release-local --repo-deploy-snapshots libs-snapshot-local

            # Run install and publish
            - ./jfrog rt mvn clean install -U -B javadoc:jar source:jar
            - ./jfrog rt bag
            - ./jfrog rt bp
            - if [ $res_jenkinsSnapshotGit_isPullRequest = "True" ]; then
                update_commit_status jenkinsSnapshotGit --context "$int_jfrog_rt_url/webapp/#/builds/$JFROG_CLI_BUILD_NAME/$JFROG_CLI_BUILD_NUMBER" --message=""
              fi

          onComplete:
            - *UPDATE_COMMIT_STATUS

            # Show tests in the *Tests* tab
            - save_tests $res_jenkinsSnapshotGit_resourcePath/target/surefire-reports/

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home
