updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status yahavGit --context "$step_name"

pipelines:
  - name: build_jenkins_snapshot_yahav
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: yahavGit
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_yahavGit_resourcePath

            # Set env
            - export CI=true
            - MVN_PATH=`which mvn` && export M2_HOME=`readlink -f $MVN_PATH | xargs dirname | xargs dirname`
            - export JFROG_CLI_BUILD_NAME=jenkins-plugin-dev
            - export JFROG_CLI_BUILD_NUMBER=$run_number

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Run install and publish
            - >
              env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              ./jfrog rt mvn clean install
            - ./jfrog rt bag
            - ./jfrog rt bp

          onComplete:
            - *UPDATE_COMMIT_STATUS
            - STEP_URL=https://oss.jfrog.org/artifactory/webapp/builds/jenkins-plugin-dev/34 update_commit_status yahavGit --context "Artifactory Build Info"

            # Show tests in the *Tests* tab
            - save_tests $res_yahavGit_resourcePath/target/surefire-reports/

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home
